"""
Default prompts module - Community version with standard prompts.
Copy this folder to /private and customize as needed.
"""

from .grading import SEVERITY_INSTRUCTIONS, MOOD_DESCRIPTIONS, GRADING_PROMPT_TEMPLATE
from .generator import QUIZ_FORMAT, DIFFICULTY_INSTRUCTIONS, GENERATION_PROMPT_TEMPLATE
from .anomaly import INDIVIDUAL_ANALYSIS_PROMPT_TEMPLATE, CLASS_ANALYSIS_PROMPT_TEMPLATE

__all__ = [
    'SEVERITY_INSTRUCTIONS',
    'MOOD_DESCRIPTIONS',
    'GRADING_PROMPT_TEMPLATE',
    'QUIZ_FORMAT',
    'DIFFICULTY_INSTRUCTIONS',
    'GENERATION_PROMPT_TEMPLATE',
    'INDIVIDUAL_ANALYSIS_PROMPT_TEMPLATE',
    'CLASS_ANALYSIS_PROMPT_TEMPLATE',
]
